name:                graphics-binding
version:             0.1.0.0
github:              "githubuser/graphics-binding"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/graphics-binding#readme>

dependencies:
- base >= 4.7 && < 5
- gl
- GLFW-b
- lens
- classy-prelude
- StateVar
- ObjectName
- vector
- linear
- bytestring
- foreign-resource

library:
  source-dirs: lib
  exposed-modules: Graphics.Binding
