name:                haskell-graphics-binding
version:             0.1.0.0
github:              "https://github.com/InThisStyle10s6p/haskell-graphics-binding"
license:             BSD3
author:              "In This Style 10/6"
maintainer:          "In This Style 10/6"
copyright:           "2018 In This Style 10/6"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/InThisStyle10s6p/haskell-graphics-binding#readme>

dependencies:
- base >= 4.7 && < 5
- gl
- GLFW-b
- lens
- vector
- linear
- bytestring
- foreign-resource-hs == 0.1.0.0

library:
  source-dirs: lib
  exposed-modules: Graphics.Binding
